### ISSUE TITLE
[Fedora 20] VDPAU related crashing

### ISSUE THREAD

**Issue by breed808** [xylosper/cmplayer#124]
I'm receiving the following error when attempting to run CMPlayer in Fedora 20: http://pastebin.com/hh8W5pKe

I'm using this specfile to build CMPlayer: http://pastebin.com/vSAEBXm7

It seems that libvdpau_nvidia.so cannot be found, despite it being located in /usr/lib64/vdpau/libvdpau_nvidia.so on my system.

I'm not sure if it's a packaging or build issue; any help would be great.

**Comment by xylosper** [comment]
Okay, thank you for reporting. Close this.
