### ISSUE TITLE
[Fedora 20] [fglrx] Cannot make OpenGL context current

### ISSUE THREAD

**Issue by sl1msn1per** [xylosper/cmplayer#139]
My cmplayer was was working just fine until I installed the proprietary ATI catalyst driver. My computer is working normally except when I run cmplayer I get the following message:

[OpenGL] Cannot make OpenGL context current!

I'm using the cmplayer from the breed808 repo - reinstalling with yum reinstall does not solve the issue.
Running mpv normally works fine, with opengl output.

**Comment by xylosper** [comment]
Close for now. If you have problem with next version(I think I can release it in this month), please reopen this.
