### ISSUE TITLE
does not play incomplete files

### ISSUE THREAD

**Issue by evsh** [xylosper/cmplayer#153]
mplayer (mpv) was always able to play partially downloaded files (I mean when they are downloaded in multichunk mode, when there are gaps inside). However, cmplayer crashes at these gaps.  It triggers assertion:

cmplayer: ../ta/ta.c:333: ta_dbg_check_header: Assertion `h->canary == 0xD3ADB3EF' failed.

This is really pity. I configure it with
./configure--qmake=/usr/lib64/qt5/bin/qmake  --prefix=/usr --disable-jack --disable-portaudio --enable-pulseaudio --enable-cdda

**Comment by xylosper** [comment]
No update. Close.
