### ISSUE TITLE
no ./waf to build mpv

### ISSUE THREAD

**Issue by salamanderrake** [xylosper/cmplayer#155]
make
./build-mpv: line 21: ./waf: No such file or directory
./build-mpv: line 21: ./waf: No such file or directory
./build-mpv: line 21: ./waf: No such file or directory
./build-mpv: line 22: ./waf: No such file or directory
Makefile:53: recipe for target 'build/lib/libmpv.a' failed
make: *** [build/lib/libmpv.a] Error 127

******************
OpenSuse 13.2

**Comment by xylosper** [comment]
No update. Close.
