### ISSUE TITLE
MPEG2 is jerky with hardware acceleration

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/cmplayer#160]
Test flie: ftp://serv.valdikss.org.ru/Anime/_DVDs/Ippatsu%20kikimusume/VTS_01_1.VOB

**Comment by xylosper** [comment]
Which backend do you use and what is your graphics card?

**Comment by ValdikSS** [comment]
I use VAAPI with Intel HD3000. It worked fine on earlier builds (maybe two months ago), I'll bisect asap.  
There are a lot of messages like this in log:
~~~
[VA-API] No usable SurfaceID. Decoding could fail
~~~

**Comment by ValdikSS** [comment]
This is regression from 0fadeed8cb2a87d02cb8e20ceb1c3b256724518a

**Comment by xylosper** [comment]
Okay, I think this is a duplication of #147

**Comment by xylosper** [comment]
Merged. If the problem still exists, please let me know. Thank you!

**Comment by ValdikSS** [comment]
Thank you!
