### ISSUE TITLE
통합 자막에서 특정 언어만 선택

### ISSUE THREAD

**Issue by dontdieych** [xylosper/cmplayer#163]
동영상이 시작 될 때 자동으로 KRCC 부분만 표시되게 하고 싶습니다.

또 다른 문제가 있는데, KRCC만 선택된 상황에서 자막 설정을 변경하고 저장 하면 ENCC도 다시 활성화 됩니다.

**Comment by xylosper** [comment]
> 동영상이 시작 될 때 자동으로 KRCC 부분만 표시되게 하고 싶습니다.

다음 버전에서 인터페이스가 좀 바뀌는데, 0.8.16이면 아마 설정>자막>우선 순위 항목이 있을 겁니다.
여기에 KRCC를 추가해보세요.

> 또 다른 문제가 있는데, KRCC만 선택된 상황에서 자막 설정을 변경하고 저장 하면 ENCC도 다시 활성화 됩니다.

최근에 컴퓨터에 들어있던 동영상들을 다 날리는 바람에 지금 통합 자막이 없어서 확인하는데 시간이 좀 걸릴 듯합니다.

**Comment by xylosper** [comment]
> 자막 설정을 변경하고 저장 하면 

이게 무슨 뜻인가요?

**Comment by dontdieych** [comment]
ENCC, KRCC 둘 다 켜져 있어서 ENCC를 끄고 영상을 보다가 설정 창을 열고 자막에 관련된 설정을 바꾼 후 확인을 누르면
비활성화 시킨 ENCC가 다시 활성화 됩니다.

**Comment by xylosper** [comment]
수정되었습니다. 감사합니다.

**Comment by dontdieych** [comment]
감사합니다.
