### ISSUE TITLE
yle-dl support

### ISSUE THREAD

**Issue by ahjolinna** [xylosper/cmplayer#166]
could it be possible to add support for yle-dl, the video streaming services of the Finnish national broadcasting company Yle: Yle Areena and Elävä Arkisto.
https://github.com/aajanki/yle-dl

**Comment by xylosper** [comment]
Does yle-dl actualy work for you? I've teset the example in the github page but it didn't work.

**Comment by ahjolinna** [comment]
@xylosper : it works for me just fine, I just updated the ccr pkgbuild. The aur version is not uptodate (http://chakraos.org/ccr/packages.php?ID=6092)

I just tested with this: yle-dl http://areena.yle.fi/tv/2409251

**Comment by xylosper** [comment]
Can you play the result of `yle-dl --showurl http://areena.yle.fi/tv/2409251` in any player?
I couldn't play it in both of mpv and mplayer.

**Comment by ahjolinna** [comment]
@xylosper: yeah it seems it does not work, I will make a bug report to the dev

**Comment by xylosper** [comment]
Once it's solved, I can add yle support, although I hope youtube-dl brings yle support.
One person requested yle support in youtube-dl over one year ago(https://github.com/rg3/youtube-dl/issues/1574) and it seems that the youtube-dl dev still considers it.

**Comment by ahjolinna** [comment]
@xylosper: plz check the dev's answer : aajanki/yle-dl#51

**Comment by xylosper** [comment]
Okay. In that case, you'd better make a feature request for mpv to support HDS.

**Comment by xylosper** [comment]
Btw, the method which yle-dl dev told you works for you? I cannot play with mplayer in that way, either.

**Comment by ahjolinna** [comment]
@xylosper : I just arrived home and tried it...and it seems not -_-

**Comment by ahjolinna** [comment]
@xylosper : quote form the dev. "According to Google you sometimes need to give -cache option to mplayer when playing from stdin:
yle-dl --pipe http://areena.yle.fi/tv/2409251 | mplayer -cache 1024 - "

It worked for me with mpv and mplayer2

**Comment by xylosper** [comment]
Okay, I'll try what I can do.
However, I think it would be better for FFmpeg to include HDS support fundamentally.
There's already an issue for this: http://trac.ffmpeg.org/ticket/1964
And you can find some forks which implements HDS in FFmpeg but I cannot find any progression.

**Comment by xylosper** [comment]
Done. Thank you.

**Comment by ahjolinna** [comment]
@xylosper : nice, it works thanks

**Comment by ahjolinna** [comment]
@xylosper : it seems it generates Cookies.txt file to the home folder

**Comment by xylosper** [comment]
Are you sure? I don't have such file.

**Comment by ahjolinna** [comment]
I got this: https://paste.kde.org/poqhrkwfo
after trying to watch this http://areena.yle.fi/tv/2449056

**Comment by xylosper** [comment]
Always whenever view it after removed the Cookies.txt?
I'm not sure but you'd better talk with yle-dl dev because there's nothing about cookie in yle-dl as far as I can see.

**Comment by ahjolinna** [comment]
@xylosper : the dev. said this: "Cookies.txt is a temporary file created by AdobeHDS.php. AdobeHDS fails to remove the file if it is terminated abnormally. yle-dl now tries to remove Cookies.txt even if AdobeHDS dies with a signal. The check is not completely fail-safe but the file should get deleted in most cases."

**Comment by xylosper** [comment]
Anyway, there's nothing I can do about this.
Since yle-dl does not accept SIGTERM gracefully, I have to kill it if playback stopped.
I cannot delete the file arbitrarily because it's created in home directory and I cannot tell the file created by yle-dl from other files.
If there's any problem, it should be fixed in yle-dl side.
