### ISSUE TITLE
Skeen Breeze

### ISSUE THREAD

**Issue by freeniki** [xylosper/cmplayer#169]
More thanks for new release )))
New skin Breeze for CMPlayer.
Download: https://sites.google.com/site/mykubikfiles2/breeze-cmplayer.tar.gz
Autor: varlesh
License: Free
![cmplayer](https://cloud.githubusercontent.com/assets/8083855/5695845/e2603a88-99c5-11e4-88d2-782ec4355864.png)

**Comment by xylosper** [comment]
Greate work! It's added to repository. Thank you.

**Comment by ahjolinna** [comment]
@freeniki : dark version would be nice, could you make one?

**Comment by freeniki** [comment]
Yes. Later made Dark Breeze ​​version.
