### ISSUE TITLE
Skeen Breeze Dark

### ISSUE THREAD

**Issue by freeniki** [xylosper/cmplayer#170]
Download: https://sites.google.com/site/mykubikfiles2/cmplayer-breeze-dark.tar.gz
Autor: varlesh
License: Free
![snapshot2](https://cloud.githubusercontent.com/assets/8083855/5697020/9ac8da06-99f5-11e4-93aa-828c75b66618.png)

**Comment by xylosper** [comment]
Good. Thank you!

**Comment by ahjolinna** [comment]
@freeniki : nice, thanks
