### ISSUE TITLE
해결 했습니다. 죄송합니다.

### ISSUE THREAD

**Issue by yueunseon** [xylosper/cmplayer#171]
어제까지 잘 되다가 갑자기 기본 프로그램으로 실행이 안됩니다.
다른 프로그램으로 기본 설정 후 실행을 하면 그때뿐이고
다시 실행하면 토템으로 플레이가 되요.
아.. 다른 문제는 해결했는데 이건 왜이럴까요?

토템을 지웠습니다.
리눅스 설정이 뭐가 좀 꼬였나보네요.
잘 쓰고 있습니다.
감사합니다.

**Comment by xylosper** [comment]
무슨일이 있었는지 잘 모르겠지만 해결되셨다니 다행입니다 :)
