### ISSUE TITLE
Sharpen and blur filters are unbelievably slow with chroma upsamplers

### ISSUE THREAD

**Issue by ValdikSS** [xylosper/cmplayer#52]
When used with any chroma upscaler except bicubic, enabling sharpen or blur filters makes video from video to slideshow with 1-3 fps, making video almost unplayable.

How to reproduce:
1. Open video file
2. Set chroma upscaler to everything except bicubic (i,e, Fast Lanczos)
3. Enable sharpen or blur filter

Expected result:
Video is sharpened or blurred without much dropped frames

Actual result:
Video is sharpened or blurred, but >80% frames are dropped

**Comment by xylosper** [comment]
Sharpen and blur effects are dropped now. So I close this.
But still, highquality of chroma upscailing requires lots of operations and it could cause massive frame drop.
